### ISSUE TITLE
No results for HTTP or Queue logs

### ISSUE THREAD

**Issue by dmason30** [laravel/vapor-ui#16]
- Vapor UI Version: 0.0.6
- Laravel Version: 8.1.0
- PHP Version: 7.4
- Database Driver & Version: MySQL 8.0

The below is the same on test/stage and production.

If I go to the Queue or HTTP logs I never get any results. 
The HTTP page polls for a while and then says no results found. 
The Queue page just seems to endlessly poll for new results but never gets any.

Is there a setting in AWS I need to enable to get output for these sections?

I get logs for CLI with the `schedule:run` output. 

![image](https://user-images.githubusercontent.com/20278756/93122282-23057200-f6be-11ea-80ae-a28eee4be2f7.png)

I also have results on the great new `Metrics` page. 
![image](https://user-images.githubusercontent.com/20278756/93122392-4b8d6c00-f6be-11ea-8483-2b60d2b19bc4.png)

## vapor.yml 
```yaml
environments:
  production:
    timeout: 900
    gateway-version: 2
    runtime: php-7.4
    cache: xxxxx
    cli-concurrency: 10
    cli-memory: 256
    cli-timeout: 900
    concurrency: 30
    database: xxxxx
    domain: xxxxx
    memory: 256
    storage: xxxxx
    queue-concurrency: 10
    queue-memory: 256
    warm: 5
```
