### ISSUE TITLE
Queue name is displayed as array

### ISSUE THREAD

**Issue by mo7zayed** [laravel/vapor-ui#84]
- Vapor UI Version: 1.4
- Laravel Version: 9
- PHP Version: 9.48.0
- Database Driver & Version: mysql 8

### Description:
I saw the vapor update related to [controlling the queue concurrency](https://blog.laravel.com/vapor-individual-queue-concurrency), I have updated my vapor.yml config to be like
```yml
    queues:
      - queue-1-production: 25
      - queue-2-production: 25
      - queue-3-production: 25
```
But the result I got is
![image](https://user-images.githubusercontent.com/21959069/215633620-7b3cb107-ebdd-47db-b5bd-b6c3b8c6944e.png)

it also results the following error in http logs
![image](https://user-images.githubusercontent.com/21959069/215634853-e45d1b7d-5384-46c6-9e7c-7a3e3f06303f.png)

### Steps To Reproduce:
- a new laravel app
- install required vapor packages (ui, core)
- configure queues to be like the example above in vapor.yml file
- deploy and go to vapor-ui dashboard
